config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  devise_for :users,  :controllers => { registrations: 'registrations' }
  get 'home/index'
  root 'coffee_bars#index'
  
  resources :coffee_bars do
	resources :comments
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/coffee_bar.rb
class CoffeeBar < ApplicationRecord
	ratyrate_rateable "ambient", "coffee", "service","visuality"
	has_many :comments
	validates :name, presence: true
	validates :address, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :coffee_bar
  validates :body, presence: true
end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  ratyrate_rater
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/coffee_bars_controller.rb
class CoffeeBarsController < ApplicationController

def show
    @bar = CoffeeBar.find(params[:id])
end

def index
	@bars=CoffeeBar.all
	@ratingCaches=RatingCache.all
end

def new
	@coffee_bar=CoffeeBar.new
end

def create
	@coffee_bar = CoffeeBar.new(bar_params)
 
  if @coffee_bar.save
    redirect_to coffee_bars_path
  else
    render 'new'
  end
end

def edit
	@coffee_bar=CoffeeBar.find(params[:id])
end

def update
  @coffee_bar = CoffeeBar.find(params[:id])
 
  if @coffee_bar.update(bar_params)
    redirect_to coffee_bars_path
  else
    render 'edit'
  end
end

def destroy
  @coffee_bar = CoffeeBar.find(params[:id])
  @coffee_bar.destroy
 
  redirect_to coffee_bars_path
end

def bar_params
    params.require(:coffee_bar).permit(:name, :string, :address, :string, :info, :text)
  end


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
def create
    @bar = CoffeeBar.find(params[:coffee_bar_id])
    @comment = @bar.comments.create(comment_params)
    redirect_to coffee_bar_path(@bar)
  end
  
  def destroy
	@bar = CoffeeBar.find(params[:coffee_bar_id])
    @comment = @bar.comments.find(params[:id])
    @comment.destroy
    redirect_to coffee_bar_path(@bar)
  end
  
  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/rater_controller.rb
class RaterController < ApplicationController

  def create
    if user_signed_in?
      obj = params[:klass].classify.constantize.find(params[:id])
      obj.rate params[:score].to_f, current_user, params[:dimension]

      render :json => true
    else
      render :json => false
    end
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:email, :password, :password_confirmation, :admin)
  end

  def account_update_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :current_password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/coffee_bars_helper.rb
module CoffeeBarsHelper

def average_rating_for_bar(bar,ratingCaches)
	sum=0.0
	avgs=[]
	ratingCaches.each do |rating|
	  if rating.cacheable_id==bar.id
		avgs<<rating.avg 
	  end
	end
	
	avgs.each do |avg|
		sum+=avg
	end
	
	if avgs.length==0
		return 0.0
	else
		return (sum/avgs.length).round(1)
	end
end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/rating_helper.rb
module RatingHelper

 #override rating_for_user helper method
	def rating_for_user(rateable_obj, rating_user, dimension = nil, options = {})
		@object = rateable_obj
		@user   = rating_user
		@rating = Rate.find_by_rater_id_and_rateable_id_and_dimension(@user.id, @object.id, dimension)
		stars = @rating ? @rating.stars : 0

		star         = options[:star]         || 5
		enable_half  = options[:enable_half]  || false
		half_show    = options[:half_show]    || true
		star_path    = options[:star_path]    || ""
		star_on      = options[:star_on]      || asset_path('star-on.png')
		star_off     = options[:star_off]     || asset_path('star-off.png')
		star_half    = options[:star_half]    || asset_path('star-half.png')
		cancel       = options[:cancel]       || false
		cancel_place = options[:cancel_place] || "left"
		cancel_hint  = options[:cancel_hint]  || "Cancel current rating!"
		cancel_on    = options[:cancel_on]    || asset_path('cancel-on.png')
		cancel_off   = options[:cancel_off]   || asset_path('cancel-off.png')
		noRatedMsg   = options[:noRatedMsg]   || "I'am readOnly and I haven't rated yet!"
		# round        = options[:round]        || { down: .26, full: .6, up: .76 }
		space        = options[:space]        || false
		single       = options[:single]       || false
		target       = options[:target]       || ''
		targetText   = options[:targetText]   || ''
		targetType   = options[:targetType]   || 'hint'
		targetFormat = options[:targetFormat] || '{score}'
		targetScore  = options[:targetScore]  || ''

		disable_after_rate = options[:disable_after_rate] || false

		readonly=false
		if disable_after_rate
		  readonly = current_user.present? ? !rateable_obj.can_rate?(current_user.id, dimension) : true
		end

		content_tag :div, '', "data-dimension" => dimension, :class => "star", "data-rating" => stars,
					"data-id" => rateable_obj.id, "data-classname" => rateable_obj.class.name,
					"data-disable-after-rate" => disable_after_rate,
					"data-readonly" => readonly,
					"data-enable-half" => enable_half,
					"data-half-show" => half_show,
					"data-star-count" => star, #changed to star from stars to show all stars 
					"data-star-path" => star_path,
					"data-star-on" => star_on,
					"data-star-off" => star_off,
					"data-star-half" => star_half,
					"data-cancel" => cancel,
					"data-cancel-place" => cancel_place,
					"data-cancel-hint"  => cancel_hint,
					"data-cancel-on" => cancel_on,
					"data-cancel-off" => cancel_off,
					"data-no-rated-message" => noRatedMsg,
					# "data-round" => round,
					"data-space" => space,
					"data-single" => single,
					"data-target" => target,
					"data-target-text" => targetText,
					"data-target-format" => targetFormat,
					"data-target-score" => targetScore
  end

end

app/views/coffee_bars/_form.html.erb
<%= form_with model: @coffee_bar, local: true do |form| %>
 
  <% if @coffee_bar.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@coffee_bar.errors.count, "error") %> prohibited
        this coffee bar from being saved:
      </h2>
      <ul>
        <% @coffee_bar.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>
 
  <p>
    <%= form.label :address %><br>
    <%= form.text_field :address %>
  </p>
  
  <p>
    <%= form.label :info %><br>
    <%= form.text_area :info %>
  </p>
  
  <p>
    <%= form.submit %>
  </p>
 
<% end %>

app/views/coffee_bars/edit.html.erb
<h1> Edit coffee bar</h1>

<%= render 'form' %>
 
<%= link_to 'Back', coffee_bars_path %>

app/views/coffee_bars/index.html.erb
<% if current_user.try(:admin?) %>
	<%= link_to 'New coffeBar', new_coffee_bar_path %>
<%	end  %>

<div class="row"> 
	<div class="bar-list col-sm-8">
	  <% @bars.each do |bar| %>
	  <div class="bar-item">
		<div class="row">
			<div class="col-sm-10"></div>
			<div class="col-sm-2">
				<div class="links">
					<% if current_user.try(:admin?) %>
						<%= link_to edit_coffee_bar_path(bar) do %>
							<span class="glyphicon glyphicon-edit edit-cb black"></span>
						<% end %>
						<%= link_to coffee_bar_path(bar),
							method: :delete,
							data: { confirm: 'Are you sure?' } do %>
							<span class="glyphicon glyphicon-remove remove-cb black"></span>
						<% end %>
					<% end %>
				</div>
			</div>
		</div>
		<%= link_to coffee_bar_path(bar), class: "more-info-btn black" do %>		
			<div class="row">
				<div class="col-sm-9">
					<h1 id="bar-name"><%= bar.name %></h1>
					<p><%= bar.address %></p>
					
				</div>
				<div class="col-sm-3">
					<div class="general-star">	
						General: 
						<div class="general-average-star">
							<p class="general-average-value"><%= average_rating_for_bar(bar,@ratingCaches) %></p>
						</div>
					</div>
					<p id="num-of-comments"><%= bar.comments.length %> comments</p> 
				</div>
			</div>
			
		<% end %>
		</div>
		
	  <% end %>
	</div>
</div>

app/views/coffee_bars/new.html.erb
<h1> New coffee bar</h1>

<%= form_with model: @coffee_bar, local: true do |form| %>
 
  <% if @coffee_bar.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@coffee_bar.errors.count, "error") %> prohibited
        this coffee bar from being saved:
      </h2>
      <ul>
        <% @coffee_bar.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>
 
  <p>
    <%= form.label :address %><br>
    <%= form.text_field :address %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
 
<% end %>

app/views/coffee_bars/show.html.erb
<div class="row">
	<div class="col-sm-6">
		<h1 id="bar-name-show">
			<%= @bar.name %>
		</h1> 
		<p id="bar-address-show">
			<%= @bar.address %>

		</p>
		</br>
		<p class="bar-info-show">
			<%= @bar.info %>
		</p>	
		</br>
		<% if current_user %>
			<div class="col-sm-6">
			  <p class="bar-info-show">Ambient:</p>
			  <%= rating_for_user @bar, current_user, "ambient",star: 5 %>
			  </br>
			  <p class="bar-info-show">Coffee:</p>
			  <%= rating_for_user @bar, current_user, "coffee", star: 5 %>
			  </br>
			</div>
			<div class="col-sm-6">
			  <p class="bar-info-show">Service:</p>
			  <%= rating_for_user @bar, current_user, "service", star: 5 %>
			  </br>
			  <p class="bar-info-show">Visuality:</p>
			  <%= rating_for_user @bar, current_user, "visuality", star: 5 %> 
			  </br>
			</div>
		<% else %>
			<div class="row">
				<div class="averages bar-info-show col-sm-2">
					Ambient:
					<%= rating_for @bar, "ambient", imdb_avg: true, disable_after_rate: true %>
				</div>
				<div class="averages bar-info-show col-sm-2">
					Coffee:
					<%= rating_for @bar, "coffee", imdb_avg: true, disable_after_rate: true %>
				</div>
				<div class="averages bar-info-show col-sm-2">
					Service:
					<%= rating_for @bar, "service", imdb_avg: true, disable_after_rate: true %>
				</div>
				<div class="averages bar-info-show col-sm-2">	
					Visuality:
					<%= rating_for @bar, "visuality", imdb_avg: true, disable_after_rate: true %>
				</div>
			</div>
		<% end %>
	</div>

	<div class="col-sm-6">
		<h2>Comments</h2>
		<div class="comment-list">
			<%= render @bar.comments %>
		</div>
		<%= render 'comments/form' %>
	</div>
</div>
<%= link_to 'Back', coffee_bars_path %>

app/views/comments/_comment.html.erb

<div class="comment-item">
	<div class="author-div">
		<h4 class="comment-author">
			<%= comment.commenter %>
		</h4>
		<div class="delete-comm-icon">
			 <% if current_user.try(:admin?) %>
				<%= link_to [comment.coffee_bar, comment], method: :delete,
					data: { confirm: 'Are you sure?' } do %>
					<span class="glyphicon glyphicon-remove red"></span>
				<% end %>
			<% end %>
		</div>
	</div>

	<p class="comment-body">
	  <%= comment.body %>
	</p>
</div>

app/views/comments/_form.html.erb

<%
if current_user
  user_name = current_user.email
else
  user_name = "Anonymous"
end
%>

<%= form_with(model: [ @bar, @bar.comments.build ]) do |form| %>
  <p>
    <%= form.hidden_field :commenter, value:user_name %>
  </p>
  <div class="row">
	<div class="col-sm-9">
		<p>
			<%= form.text_area :body, placeholder: "Write a comment", class: "comment-text-area" %>
		</p>
	</div>
	<div class="col-sm-2">
		<p>
			<%= form.submit "Comment" %>
		</p>
	</div>
  
<% end %>

app/views/home/index.html.erb
<h1>Home#index</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RateCoffeeBar</title>
	<link rel="shortcut icon" href="/assets/coffee-cup.png" />

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

	<nav class="navbar navbar-inverse navbar-static-top">
		<div class="navbar-header">
		  <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
			<span class="sr-only">Toggle Navigation</span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
		  </button>
		  <%= link_to "RateCoffeeBar",coffee_bars_path, :class => 'navbar-brand' %>
		</div> 
		<div class="collapse navbar-collapse navbar-right">
		  <ul class="nav navbar-nav">
			<% if user_signed_in? %>
			<li class="navbar-text"> Logged in as <strong><%= current_user.email %></strong>.</li>
			<li class="nav-item"><%= link_to edit_user_registration_path, :class => 'navbar-link' do %>
				<span class="glyphicon glyphicon-edit"> Edit</span>
			<% end %>
			</li>
			<li class="nav-item"><%= link_to destroy_user_session_path, method: :delete, :class => 'navbar-link'  do %>
				<span class="glyphicon glyphicon-log-out"> Logout</span>
			<% end %>
			</li>
		<% else %>
			<li class="nav-item"><%= link_to new_user_registration_path, :class => 'navbar-link' do %>
				<span class="glyphicon glyphicon-user"> Signup</span>
			<% end %>
			</li>
			<li class="nav-item"><%= link_to new_user_session_path, :class => 'navbar-link'  do %>
				<span class="glyphicon glyphicon-log-in"> Login</span>
			<% end %>
			</li>
		<% end %>
		  </ul> 
		</div> 
	</nav>
	<div class="container">    
		<% if notice %>
			<p class="alert alert-success"><%= notice %></p>
		<% end %>
		<% if alert %>
			<p class="alert alert-danger"><%= alert %></p>
		<% end %>
		<%= yield %>
	</div>
  </body>
</html>